### ISSUE TITLE
windowに締め切りフラグが必要

### ISSUE THREAD

**Issue by genya0407** [kumano-dormitory/jimuto#7]
締め切るときに、すべてのshiftに1つ以上のrequestが登録されているかを判定し、空のshiftがあれば締め切らせない。

**Comment by shiba6v** [comment]
windowにEnumでフェーズをつける。
request_phase リクエストを募集する段階。リクエスト締め切りボタンを押すと、次へ。
solution_phase 解決案を募集する段階。解決案確定ボタンを押すと、次へ。バリデーションメソッドを設ける。
fixed_phase 解決案が固まってシフト表が確定した状態。管理者のみが押せる事務当終了ボタンで、次へ。
finished_phase 事務当番が終了した状態。今回はwindows/ からは見えなくする。ハッカソン終了後にでも過去の記録が見えるようにしたい。
